git add codemagic.yaml
git commit -m 'Add first workflow'
git push

workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: 3.19.0
      xcode: 15.3
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          flutter build ios --release
