environment:
  flutter: "3.19.0"

scripts:
  pre:
    - flutter --version  # Optional: to verify correct version is used
    - flutter pub get

git add codemagic.yaml
git commit -m 'Add first workflow'
git push
