workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: 15.3
    scripts:
      - name: Confirm Flutter & Dart Version
        script: |
          flutter --version

      - name: Install Dart and Flutter dependencies
        script: |
          flutter pub get

      - name: Build iOS release (generates Flutter.framework)
        script: |
          flutter build ios --release

    artifacts:
      - build/ios/ipa
