# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics disabled
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Prevent building simulator slices of certain pods
def flutter_ios_podfile_fix
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end

# Flutter Pod integration
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), __dir__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  install_all_flutter_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  flutter_ios_podfile_fix

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # Force deployment target for all pods
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
